### ISSUE TITLE
Could you publish gem to rubygems :question:

### ISSUE THREAD

**Issue by camelmasa** [pepabo/omniauth-colormeshop#2]
Maybe, the gem isn't published to rubygems :star: 
https://rubygems.org/search?utf8=%E2%9C%93&query=omniauth-colormeshop

If possible, could you publish gem to rubygems :shipit:

**Comment by kentaro** [comment]
Are you going to use this library somewhere? I'm just gotten interested, though.
Anyway, will publish it asap.

**Comment by kentaro** [comment]
Shipped https://rubygems.org/gems/omniauth-colormeshop

**Comment by camelmasa** [comment]
Thank you for response and published :+1: 

Yea, we are creating "sync inventories system" (like [zaiko robot](http://www.zaiko-robot.com/)).
We think to use color me shop API from OAuth2 for that.

**Comment by kentaro** [comment]
Sounds interesting! Looking forward to see it ;)
